"""SDS v1 全量 Case 规格表 — 70 Case 单一数据源。"""

from __future__ import annotations

# (case_id, name, problem_space, intents_csv, escalation, user_goal, rules_csv)
FULL_CASE_SPECS: tuple[tuple[str, str, str, str, str, str, str], ...] = (
    # IC — Information (10)
    ("IC-001", "查询订单状态", "PS-01", "QueryOrder", "P3", "确认订单存在与支付状态", ""),
    ("IC-002", "订单不存在", "PS-01", "QueryOrder", "P2", "确认是否支付成功或账号正确", "OrderNotFound"),
    ("IC-003", "查询订单详情", "PS-01", "QueryOrder", "P3", "了解套餐内容与履约要求", ""),
    ("IC-004", "查询券状态", "PS-01", "QueryVoucher,CheckVoucherAvailability", "P3", "确认券是否可用", ""),
    ("IC-005", "查询券码", "PS-01", "QueryVoucher", "P3", "获取核销码完成到店消费", ""),
    ("IC-006", "查询券有效期", "PS-01", "QueryVoucher", "P3", "确认是否在有效期内", ""),
    ("IC-007", "查询优惠券状态", "PS-01", "QueryCoupon", "P3", "理解优惠券为何不可用", ""),
    ("IC-008", "查询门店信息", "PS-01", "QueryStore", "P3", "获取地址/营业时间以便到店", ""),
    ("IC-009", "查询预约状态", "PS-01", "QueryReservation,CheckReservationEligibility", "P3", "确认预约是否生效", ""),
    ("IC-010", "查询退款状态", "PS-01", "QueryRefund", "P3", "跟踪售后进度", ""),
    # PC — Platform (15)
    ("PC-001", "已支付未出单", "PS-04", "QueryOrder,VoucherUnavailable", "P0", "确认支付并获取可用券", "OrderMissing"),
    ("PC-002", "订单状态异常", "PS-04", "QueryOrder", "P2", "恢复订单正常状态", "OrderStatusInvalid"),
    ("PC-003", "重复订单", "PS-04", "QueryOrder", "P2", "确认是否重复下单并处理", "DuplicateOrder"),
    ("PC-004", "券不存在", "PS-04", "VoucherUnavailable,QueryVoucher", "P2", "找到或补发可用券", "VoucherMissing"),
    ("PC-005", "券已过期", "PS-03", "VoucherUnavailable,CheckVoucherAvailability", "P2", "终止或挽回损失", "VoucherExpired"),
    ("PC-006", "券已核销", "PS-03", "VoucherUnavailable", "P2", "确认是否重复核销", "VoucherRedeemed"),
    ("PC-007", "券冻结", "PS-03", "VoucherUnavailable", "P2", "解除冻结或升级处理", "VoucherFrozen"),
    ("PC-008", "券适用门店不匹配", "PS-03", "VoucherUnavailable", "P2", "找到可核销门店", "VoucherStoreMismatch"),
    ("PC-009", "券适用时间不匹配", "PS-03", "VoucherUnavailable", "P2", "选择合规时段消费", "VoucherTimeMismatch"),
    ("PC-010", "需要预约未预约", "PS-04", "VoucherUnavailable,ReservationFailure", "P2", "完成预约后履约", "ReservationMissing"),
    ("PC-011", "核销二维码失效", "PS-04", "VoucherUnavailable", "P2", "刷新码或改手动核销", "QRCodeInvalid"),
    ("PC-012", "优惠券过期", "PS-03", "QueryCoupon", "P2", "理解限制并选替代", "CouponExpired"),
    ("PC-013", "优惠券门槛未满足", "PS-02", "QueryCoupon,CheckVoucherAvailability", "P3", "满足门槛或换券", "CouponThresholdNotMet"),
    ("PC-014", "优惠券不可叠加", "PS-02", "QueryCoupon", "P3", "选择可用优惠组合", "CouponStackingDenied"),
    ("PC-015", "活动结束", "PS-03", "VoucherUnavailable,MerchantReject", "P2", "确认活动规则或售后", "CampaignEnded"),
    # FC — Fulfillment (20)
    ("FC-001", "门店暂停营业", "PS-04", "StoreUnavailable,VoucherUnavailable", "P1", "改期或替代履约", "StoreSuspended"),
    ("FC-002", "门店永久闭店", "PS-04", "StoreUnavailable", "P1", "退款或转店", "StoreClosed"),
    ("FC-003", "门店搬迁", "PS-04", "StoreUnavailable,QueryStore", "P2", "获取新地址并确认可履约", "StoreRelocated"),
    ("FC-004", "门店电话无法接通", "PS-04", "StoreUnavailable,QueryStore", "P2", "联系商家或建单协助", "MerchantUnreachable"),
    ("FC-005", "门店超负荷经营", "PS-04", "StoreUnavailable,ServiceMismatch", "P2", "错峰或改约", "StoreOverCapacity"),
    ("FC-006", "商家拒绝核销", "PS-04", "MerchantReject,VoucherUnavailable", "P1", "完成核销或升级", "MerchantRejectService"),
    ("FC-007", "商家声称活动结束", "PS-04", "MerchantReject", "P1", "核实平台规则", "CampaignEnded"),
    ("FC-008", "系统核销失败", "PS-04", "VoucherUnavailable", "P2", "恢复核销能力", "SystemVerificationFailed"),
    ("FC-009", "预约失败", "PS-04", "ReservationFailure", "P2", "改约或换店", "ReservationFailed"),
    ("FC-010", "商家拒绝预约", "PS-04", "ReservationFailure", "P2", "联系商家或投诉", "ReservationDenied"),
    ("FC-011", "套餐内容缩水", "PS-04", "ServiceMismatch", "P0", "获得应有服务或补偿", "ServiceMismatch"),
    ("FC-012", "商家拒绝接待", "PS-04", "MerchantReject,StoreUnavailable", "P0", "完成接待或升级", "MerchantRejectService"),
    ("FC-013", "商品缺货", "PS-04", "ServiceMismatch", "P2", "换货/改约/退款", "OutOfStock"),
    ("FC-014", "服务质量不达预期", "PS-04", "ServiceComplaint,ServiceMismatch", "P2", "补偿或升级", "ServiceQualityIssue"),
    ("FC-015", "服务人员态度恶劣", "PS-04", "ServiceComplaint", "P1", "记录投诉并处理", "BadAttitude"),
    ("FC-016", "强制消费", "PS-04", "ServiceMismatch", "P0", "停止强制并维权", "MerchantForceConsumption"),
    ("FC-017", "临时加价", "PS-04", "ServiceMismatch,PriceDispute", "P1", "核实价格并维权", "MerchantPriceIncrease"),
    ("FC-018", "服务人员缺席", "PS-04", "ServiceMismatch,ReservationFailure", "P2", "改约或退款", "StaffAbsent"),
    ("FC-019", "商家提前结束营业", "PS-04", "StoreUnavailable", "P2", "改期或退款", "EarlyClosure"),
    ("FC-020", "商家履约能力不足", "PS-04", "ServiceMismatch", "P2", "替代方案或退款", "InsufficientCapacity"),
    # AC — After Sale (10)
    ("AC-001", "未核销退款申请", "PS-05", "RefundRequest,CheckRefundEligibility", "P2", "终止交易挽回损失", "RefundAllowed"),
    ("AC-002", "已核销退款申请", "PS-05", "RefundRequest", "P1", "评估是否可退", "RefundReviewRequired"),
    ("AC-003", "部分履约退款", "PS-05", "RefundRequest", "P2", "按未体验部分退款", "PartialRefundAllowed"),
    ("AC-004", "退款处理中", "PS-05", "QueryRefund,RefundRequest", "P3", "了解进度", "RefundProcessing"),
    ("AC-005", "退款超时", "PS-05", "QueryRefund,AppealRequest", "P2", "催促或升级", "RefundTimeout"),
    ("AC-006", "退款失败", "PS-05", "QueryRefund,AppealRequest", "P2", "重试或申诉", "RefundFailed"),
    ("AC-007", "补偿申请", "PS-05", "CompensationRequest", "P2", "获得合理补偿", "CompensationEligible"),
    ("AC-008", "补偿进度查询", "PS-05", "CompensationRequest,QueryTicket", "P3", "了解补偿审核进度", "CompensationProcessing"),
    ("AC-009", "用户申诉", "PS-05", "AppealRequest", "P2", "申诉处理结果", "AppealPending"),
    ("AC-010", "特殊售后申请", "PS-05", "RefundRequest,AppealRequest", "P2", "特殊规则人工审核", "SpecialAfterSale"),
    # CC — Complaint (15)
    ("CC-001", "宣传与实际不符", "PS-06", "MerchantComplaint,ServiceMismatch", "P1", "核实宣传并维权", "MisleadingDescription"),
    ("CC-002", "商家虚假宣传", "PS-06", "MerchantComplaint", "P1", "举报虚假宣传", "FalseAdvertising"),
    ("CC-003", "服务态度投诉", "PS-06", "ServiceComplaint", "P1", "记录并处理", "BadAttitude"),
    ("CC-004", "服务质量投诉", "PS-06", "ServiceComplaint,ServiceMismatch", "P1", "记录并处理", "ServiceQualityIssue"),
    ("CC-005", "强制消费投诉", "PS-06", "ServiceComplaint,ServiceMismatch", "P0", "停止强制并维权", "MerchantForceConsumption"),
    ("CC-006", "临时加价投诉", "PS-06", "PriceDispute,ServiceComplaint", "P1", "核实价格并维权", "MerchantPriceIncrease"),
    ("CC-007", "商家拒绝履约投诉", "PS-06", "MerchantComplaint,MerchantReject", "P1", "督促履约或退款", "MerchantRejectService"),
    ("CC-008", "食品安全投诉", "PS-06", "SafetyComplaint", "P0", "立即升级处理", "FoodSafety"),
    ("CC-009", "人身安全投诉", "PS-06", "SafetyComplaint", "P0", "立即升级处理", "PersonalSafety"),
    ("CC-010", "商家违规行为举报", "PS-06", "MerchantComplaint", "P1", "记录举报并核查", "MerchantViolation"),
    ("CC-011", "用户权益受损", "PS-06", "MerchantComplaint,AppealRequest", "P1", "恢复权益或补偿", "RightsViolation"),
    ("CC-012", "价格争议", "PS-06", "PriceDispute", "P2", "核实价格规则", "PriceDispute"),
    ("CC-013", "恶意商家投诉", "PS-06", "MerchantComplaint", "P1", "核查并限制商家", "MaliciousMerchant"),
    ("CC-014", "平台处理结果投诉", "PS-06", "AppealRequest", "P2", "复核处理结果", "PlatformDecisionAppeal"),
    ("CC-015", "重复投诉升级", "PS-06", "AppealRequest,HumanTransfer", "P0", "升级专人处理", "RepeatComplaint"),
    # System
    ("CLARIFY", "需求澄清", "PS-01", "clarify", "P3", "探明用户真实履约诉求", ""),
    ("CHITCHAT", "闲聊引导", "PS-01", "chitchat", "P3", "建立信任并引导回履约", ""),
    ("HUMAN", "转人工服务", "PS-07", "HumanTransfer", "P1", "获得人工协助", ""),
)
