"""Generate bulk mock SQL seed data (100+ rows per entity)."""

from __future__ import annotations

import json
import random
from datetime import datetime, timedelta, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "deploy" / "init-db" / "03-bulk-seed.sql"

CITIES = ["北京", "上海", "广州", "深圳", "杭州", "成都", "武汉", "南京"]
# 明确排除「到店服务」类目；门店 metadata 不包含「商家影响能力」
CATEGORIES = ["美食", "电影演出", "休闲娱乐", "丽人美发", "酒店民宿", "KTV", "运动健身"]
MERCHANT_PREFIX = ["川巷子", "星河", "松间里", "悦食", "花间", "鹿鸣", "云栖", "青禾", "拾味", "暖居"]
SERVICE_TYPES = ["团购套餐", "电影票", "预约服务", "酒店套餐", "KTV套餐", "健身次卡"]
ORDER_STATUSES = ["unused", "scheduled", "used", "refunding", "refunded", "expired"]
VOUCHER_STATUSES = ["unused", "scheduled", "used", "refund_pending", "expired"]
COUPON_STATUSES = ["available", "unavailable", "used", "expired"]
REFUND_STATUSES = ["submitted", "processing", "approved", "rejected"]
EVENT_TYPES = ["purchase", "reservation", "arrive", "verify", "consume", "refund", "reschedule"]
ACTORS = ["user", "agent", "tool", "system"]
OPERATION_TYPES = ["query", "diagnose", "execute", "notify", "handoff"]

random.seed(42)
NOW = datetime.now(timezone.utc)


def esc(value: str) -> str:
    return value.replace("'", "''")


def sql_json(data: dict) -> str:
    return esc(json.dumps(data, ensure_ascii=False))


def main() -> None:
    lines: list[str] = ["-- Bulk mock data generated by scripts/generate_mock_data.py", ""]

    users: list[tuple] = [("user_demo", "小林", "北京", "生活服务金卡", "138****2468")]
    for i in range(1, 121):
        city = CITIES[i % len(CITIES)]
        users.append(
            (
                f"user_{i:03d}",
                f"用户{i:03d}",
                city,
                random.choice(["普通用户", "生活服务银卡", "生活服务金卡", "黑金会员"]),
                f"13{random.randint(0, 9)}****{random.randint(1000, 9999)}",
            )
        )
    lines.append("INSERT INTO users (id, display_name, city, membership_level, phone_mask) VALUES")
    lines.append(",\n".join(f"  ('{u[0]}', '{esc(u[1])}', '{u[2]}', '{u[3]}', '{u[4]}')" for u in users))
    lines.append("ON CONFLICT (id) DO NOTHING;\n")

    stores: list[tuple] = []
    for i in range(1, 121):
        cat = CATEGORIES[i % len(CATEGORIES)]
        city = CITIES[i % len(CITIES)]
        merchant = f"{MERCHANT_PREFIX[i % len(MERCHANT_PREFIX)]}{cat[:2]}"
        meta = {
            "parking": random.choice(["有停车场", "路边停车", "无停车位"]),
            "scanner_synced": random.random() > 0.15,
            "supports_manual_verify": True,
        }
        stores.append(
            (
                f"store_{i:03d}",
                merchant,
                f"{merchant}·{city}店",
                cat,
                city,
                f"{city}市示例区示例路 {i} 号",
                random.choice(["10:00-22:00", "09:30-24:00", "11:00-23:00", "12:00-02:00"]),
                f"010-{random.randint(10000000, 99999999)}",
                random.random() > 0.4,
                meta,
            )
        )
    lines.append(
        "INSERT INTO merchant_stores (id, merchant_name, store_name, category, city, address, business_hours, phone, supports_reservation, metadata) VALUES"
    )
    lines.append(
        ",\n".join(
            f"  ('{s[0]}', '{esc(s[1])}', '{esc(s[2])}', '{s[3]}', '{s[4]}', '{esc(s[5])}', '{s[6]}', '{s[7]}', {str(s[8]).upper()}, '{sql_json(s[9])}'::jsonb)"
            for s in stores
        )
    )
    lines.append("ON CONFLICT (id) DO NOTHING;\n")

    orders: list[tuple] = []
    for i in range(1, 121):
        user_id = f"user_{i:03d}" if i > 3 else "user_demo"
        store = stores[i % len(stores)]
        service_type = SERVICE_TYPES[i % len(SERVICE_TYPES)]
        status = ORDER_STATUSES[i % len(ORDER_STATUSES)]
        paid = round(random.uniform(39, 399), 2)
        original = round(paid * random.uniform(1.1, 1.6), 2)
        purchase = NOW - timedelta(days=random.randint(0, 30))
        expire = purchase + timedelta(days=random.randint(7, 45))
        meta = {
            "reservation_required": service_type in ("团购套餐", "预约服务", "酒店套餐"),
            "reservation_confirmed": status in ("scheduled", "used"),
            "people": random.randint(1, 4),
        }
        orders.append(
            (
                f"order_{i:03d}",
                user_id,
                store[0],
                service_type,
                f"{store[1]}{service_type}",
                status,
                paid,
                original,
                purchase.isoformat(),
                (purchase + timedelta(hours=random.randint(2, 72))).isoformat() if status == "scheduled" else None,
                expire.isoformat(),
                status in ("unused", "scheduled", "refunding"),
                service_type in ("电影票", "预约服务", "酒店套餐"),
                meta,
            )
        )
    lines.append(
        "INSERT INTO life_orders (id, user_id, store_id, service_type, title, status, paid_amount, original_amount, purchase_time, service_time, expire_time, can_refund, can_reschedule, metadata) VALUES"
    )
    order_values = []
    for o in orders:
        st = f"'{o[9]}'::timestamptz" if o[9] else "NULL"
        order_values.append(
            f"  ('{o[0]}', '{o[1]}', '{o[2]}', '{esc(o[3])}', '{esc(o[4])}', '{o[5]}', {o[6]}, {o[7]}, '{o[8]}'::timestamptz, {st}, '{o[10]}'::timestamptz, {str(o[11]).upper()}, {str(o[12]).upper()}, '{sql_json(o[13])}'::jsonb)"
        )
    lines.append(",\n".join(order_values))
    lines.append("ON CONFLICT (id) DO NOTHING;\n")

    vouchers: list[tuple] = []
    for i, o in enumerate(orders, start=1):
        vouchers.append(
            (
                f"voucher_{i:03d}",
                o[0],
                o[1],
                o[2],
                f"DY{i:04d}-{random.randint(1000, 9999)}",
                o[4],
                VOUCHER_STATUSES[i % len(VOUCHER_STATUSES)],
                o[8],
                o[10],
                "需按订单规则预约或到店核销，不可与其他优惠叠加。",
            )
        )
    lines.append(
        "INSERT INTO vouchers (id, order_id, user_id, store_id, code, title, status, valid_from, valid_to, usage_rule) VALUES"
    )
    lines.append(
        ",\n".join(
            f"  ('{v[0]}', '{v[1]}', '{v[2]}', '{v[3]}', '{v[4]}', '{esc(v[5])}', '{v[6]}', '{v[7]}'::timestamptz, '{v[8]}'::timestamptz, '{esc(v[9])}')"
            for v in vouchers
        )
    )
    lines.append("ON CONFLICT (id) DO NOTHING;\n")

    coupons: list[tuple] = []
    for i in range(1, 121):
        user_id = f"user_{i:03d}" if i > 2 else "user_demo"
        cat = CATEGORIES[i % len(CATEGORIES)]
        coupons.append(
            (
                f"coupon_{i:03d}",
                user_id,
                f"{cat}满 {random.randint(80, 200)} 减 {random.randint(10, 50)}",
                random.randint(10, 50),
                random.randint(80, 200),
                cat,
                stores[i % len(stores)][0] if i % 3 == 0 else None,
                COUPON_STATUSES[i % len(COUPON_STATUSES)],
                (NOW + timedelta(days=random.randint(1, 30))).isoformat(),
                "满足门槛可用，部分券不可与团购套餐叠加。",
            )
        )
    lines.append(
        "INSERT INTO coupons (id, user_id, title, discount_amount, threshold_amount, applicable_category, applicable_store_id, status, valid_to, rule_text) VALUES"
    )
    coupon_values = []
    for c in coupons:
        store_id = f"'{c[6]}'" if c[6] else "NULL"
        coupon_values.append(
            f"  ('{c[0]}', '{c[1]}', '{esc(c[2])}', {c[3]}, {c[4]}, '{c[5]}', {store_id}, '{c[7]}', '{c[8]}'::timestamptz, '{esc(c[9])}')"
        )
    lines.append(",\n".join(coupon_values))
    lines.append("ON CONFLICT (id) DO NOTHING;\n")

    refunds: list[tuple] = []
    for i in range(1, 121):
        order = orders[i % len(orders)]
        refunds.append(
            (
                f"refund_{i:03d}",
                order[0],
                order[1],
                random.choice(["商家停业", "行程变更", "券无法核销", "服务未履约", "重复购买"]),
                REFUND_STATUSES[i % len(REFUND_STATUSES)],
                order[6],
                (NOW + timedelta(days=random.randint(1, 3))).isoformat(),
            )
        )
    lines.append(
        "INSERT INTO refund_cases (id, order_id, user_id, reason, status, refundable_amount, estimated_finish_time) VALUES"
    )
    lines.append(
        ",\n".join(
            f"  ('{r[0]}', '{r[1]}', '{r[2]}', '{esc(r[3])}', '{r[4]}', {r[5]}, '{r[6]}'::timestamptz)" for r in refunds
        )
    )
    lines.append("ON CONFLICT (id) DO NOTHING;\n")

    events: list[tuple] = []
    for i in range(1, 121):
        order = orders[i % len(orders)]
        events.append(
            (
                order[0],
                order[1],
                order[2],
                EVENT_TYPES[i % len(EVENT_TYPES)],
                random.choice(["success", "failed", "pending", "cancelled"]),
                {"note": f"履约事件{i}", "channel": random.choice(["app", "store", "agent"])},
                (NOW - timedelta(hours=random.randint(1, 720))).isoformat(),
            )
        )
    lines.append(
        "INSERT INTO fulfillment_events (order_id, user_id, store_id, event_type, status, detail, created_at) VALUES"
    )
    lines.append(
        ",\n".join(
            f"  ('{e[0]}', '{e[1]}', '{e[2]}', '{e[3]}', '{e[4]}', '{sql_json(e[5])}'::jsonb, '{e[6]}'::timestamptz)"
            for e in events
        )
    )
    lines.append(";\n")

    logs: list[tuple] = []
    for i in range(1, 121):
        user_id = f"user_{i:03d}" if i > 5 else "user_demo"
        logs.append(
            (
                f"sess_{i:03d}",
                user_id,
                OPERATION_TYPES[i % len(OPERATION_TYPES)],
                ACTORS[i % len(ACTORS)],
                f"操作记录{i}：{random.choice(['查询订单', '诊断券码', '联系商家', '创建退款', '转人工'])}",
                {"step": i, "intent": random.choice(["voucher_usage", "refund", "store_fulfillment"])},
                (NOW - timedelta(minutes=random.randint(1, 10000))).isoformat(),
            )
        )
    lines.append(
        "INSERT INTO agent_operation_logs (session_id, user_id, operation_type, actor, summary, payload, created_at) VALUES"
    )
    lines.append(
        ",\n".join(
            f"  ('{l[0]}', '{l[1]}', '{l[2]}', '{l[3]}', '{esc(l[4])}', '{sql_json(l[5])}'::jsonb, '{l[6]}'::timestamptz)"
            for l in logs
        )
    )
    lines.append(";\n")

    knowledge = [
        (6, "voucher", "券码核销失败常见原因", "核销失败可能因券已过期、门店不适用、未预约、或商家扫码设备未同步。", ["核销失败", "扫不出来", "无法核销"]),
        (7, "workflow", "核销失败处置流程", "先诊断根因，再按流程执行：重新生成核销码、手动输入券码、联系商家、转人工。", ["处置", "流程", "核销"]),
        (8, "fulfillment", "履约事件追踪", "购买、预约、到店、核销、消费、售后均会记录履约事件，供 Agent 回溯。", ["履约", "事件", "追踪"]),
    ]
    lines.append("INSERT INTO knowledge_articles (id, category, title, content, keywords) VALUES")
    lines.append(
        ",\n".join(f"  ({k[0]}, '{k[1]}', '{esc(k[2])}', '{esc(k[3])}', ARRAY{list(k[4])})" for k in knowledge)
    )
    lines.append("ON CONFLICT (id) DO NOTHING;\n")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT} ({OUT.stat().st_size // 1024} KB)")


if __name__ == "__main__":
    main()
